//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSLab.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNSLab.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points a hostname to an IPv6 address.
        /// </summary>
        public static string AAAADescription {
            get {
                return ResourceManager.GetString("AAAADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete record?.
        /// </summary>
        public static string AreYouSureDel {
            get {
                return ResourceManager.GetString("AreYouSureDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanuguage {
            get {
                return ResourceManager.GetString("ChangeLanuguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Host Name.
        /// </summary>
        public static string CreateAHostName {
            get {
                return ResourceManager.GetString("CreateAHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Game Server.
        /// </summary>
        public static string CreateGameServerH2 {
            get {
                return ResourceManager.GetString("CreateGameServerH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let your friends easily connect to your Game server with No-IP Dynamic DNS, anytime, anywhere. Create a custom URL to share with your friends to start playing on your own server now..
        /// </summary>
        public static string CreateGameServerMessage {
            get {
                return ResourceManager.GetString("CreateGameServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Host Name.
        /// </summary>
        public static string CreateHostName {
            get {
                return ResourceManager.GetString("CreateHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CNAME duplicates the hostname&apos;s records.
        /// </summary>
        public static string DNSAliasDescription {
            get {
                return ResourceManager.GetString("DNSAliasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record that points a hostname to an IPv4 address.
        /// </summary>
        public static string DNSHostDescription {
            get {
                return ResourceManager.GetString("DNSHostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic DNS Update Client.
        /// </summary>
        public static string DynamicDNSUpdateClient {
            get {
                return ResourceManager.GetString("DynamicDNSUpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Host Name.
        /// </summary>
        public static string EditHostName {
            get {
                return ResourceManager.GetString("EditHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is duplicate.
        /// </summary>
        public static string Email_Is_Duplicate {
            get {
                return ResourceManager.GetString("Email_Is_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid.
        /// </summary>
        public static string Email_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Email_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your host name.
        /// </summary>
        public static string EnterYourHostName {
            get {
                return ResourceManager.GetString("EnterYourHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex.
        /// </summary>
        public static string ex {
            get {
                return ResourceManager.GetString("ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sans-serif.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName is duplicate.
        /// </summary>
        public static string HostName_Is_Duplicate {
            get {
                return ResourceManager.GetString("HostName_Is_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName is not valid.
        /// </summary>
        public static string HostName_Is_Not_Valid {
            get {
                return ResourceManager.GetString("HostName_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName Alias is not valid.
        /// </summary>
        public static string HostNameAlias_Is_Not_Valid {
            get {
                return ResourceManager.GetString("HostNameAlias_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName created.
        /// </summary>
        public static string HostNameCreated {
            get {
                return ResourceManager.GetString("HostNameCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Names.
        /// </summary>
        public static string HostNames {
            get {
                return ResourceManager.GetString("HostNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName updated.
        /// </summary>
        public static string HostNameUpdated {
            get {
                return ResourceManager.GetString("HostNameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic IP address got you down?.
        /// </summary>
        public static string IndexH1Message {
            get {
                return ResourceManager.GetString("IndexH1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an easy to remember hostname and never lose your connection again..
        /// </summary>
        public static string IndexMessage {
            get {
                return ResourceManager.GetString("IndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Address.
        /// </summary>
        public static string IPv4Address {
            get {
                return ResourceManager.GetString("IPv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Address is not valid.
        /// </summary>
        public static string IPv4Address_Is_Not_Valid {
            get {
                return ResourceManager.GetString("IPv4Address_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 Address.
        /// </summary>
        public static string IPv6Address {
            get {
                return ResourceManager.GetString("IPv6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 Address is not valid.
        /// </summary>
        public static string IPv6Address_Is_Not_Valid {
            get {
                return ResourceManager.GetString("IPv6Address_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Free.
        /// </summary>
        public static string ItsFree {
            get {
                return ResourceManager.GetString("ItsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with a free Dynamic DNS account, no credit card required..
        /// </summary>
        public static string ItsFreeMessage {
            get {
                return ResourceManager.GetString("ItsFreeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile is duplicate.
        /// </summary>
        public static string Mobile_Is_Duplicate {
            get {
                return ResourceManager.GetString("Mobile_Is_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressing.
        /// </summary>
        public static string Progressing {
            get {
                return ResourceManager.GetString("Progressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        public static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Access a Computer.
        /// </summary>
        public static string RemoteAccessComputerH2 {
            get {
                return ResourceManager.GetString("RemoteAccessComputerH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tired of remembering your IP address to Remote Access a Device? Does your IP address change constantly? Our Dynamic DNS allows you to access your devices remotely without needing a Static IP address. All you need to remember is your hostname..
        /// </summary>
        public static string RemoteAccessComputerMessage {
            get {
                return ResourceManager.GetString("RemoteAccessComputerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Will Create New HostName As IPv4(A) , IPv6(AAAA) Or CName.
        /// </summary>
        public static string SEO_DNSCreateDescription {
            get {
                return ResourceManager.GetString("SEO_DNSCreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4,IPv6,CName,A,AAAA,AliasHost,Create.
        /// </summary>
        public static string SEO_DNSCreateKeyWords {
            get {
                return ResourceManager.GetString("SEO_DNSCreateKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DNS HostName.
        /// </summary>
        public static string SEO_DNSCreateTitle {
            get {
                return ResourceManager.GetString("SEO_DNSCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Will Edit HostNames As IPv4(A) , IPv6(AAAA) Or CName.
        /// </summary>
        public static string SEO_DNSEditDescription {
            get {
                return ResourceManager.GetString("SEO_DNSEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4,IPv6,CName,A,AAAA,AliasHost,Edit.
        /// </summary>
        public static string SEO_DNSEditKeyWords {
            get {
                return ResourceManager.GetString("SEO_DNSEditKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit DNS HostName.
        /// </summary>
        public static string SEO_DNSEditTitle {
            get {
                return ResourceManager.GetString("SEO_DNSEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Windows Client For Update EndPoint IP with DNSLab.ir.
        /// </summary>
        public static string SEO_DownloadClientDescription {
            get {
                return ResourceManager.GetString("SEO_DownloadClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client,dns,app,windows,win.
        /// </summary>
        public static string SEO_DownloadClientKeyWords {
            get {
                return ResourceManager.GetString("SEO_DownloadClientKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Windows Client DNS Manager.
        /// </summary>
        public static string SEO_DownloadClientTitle {
            get {
                return ResourceManager.GetString("SEO_DownloadClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your DNS&apos;s.
        /// </summary>
        public static string SEO_MyDNSDescription {
            get {
                return ResourceManager.GetString("SEO_MyDNSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS,Hosts,HostNames.
        /// </summary>
        public static string SEO_MyDNSKeyWords {
            get {
                return ResourceManager.GetString("SEO_MyDNSKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My DNSLab.
        /// </summary>
        public static string SEO_MyDNSTitle {
            get {
                return ResourceManager.GetString("SEO_MyDNSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth To Login DNSLab.
        /// </summary>
        public static string SEO_UserAuthDescription {
            get {
                return ResourceManager.GetString("SEO_UserAuthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth,DNSLab,User,Login.
        /// </summary>
        public static string SEO_UserAuthKeyWords {
            get {
                return ResourceManager.GetString("SEO_UserAuthKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth User.
        /// </summary>
        public static string SEO_UserAuthTitle {
            get {
                return ResourceManager.GetString("SEO_UserAuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Account Information.
        /// </summary>
        public static string SEO_UserInfoDescription {
            get {
                return ResourceManager.GetString("SEO_UserInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info,Account,Update,User.
        /// </summary>
        public static string SEO_UserInfoKeyWords {
            get {
                return ResourceManager.GetString("SEO_UserInfoKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        public static string SEO_UserInfoTitle {
            get {
                return ResourceManager.GetString("SEO_UserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Free Account Today.
        /// </summary>
        public static string SEO_UserRegisterDescription {
            get {
                return ResourceManager.GetString("SEO_UserRegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register,Free,Account.
        /// </summary>
        public static string SEO_UserRegisterKeyWords {
            get {
                return ResourceManager.GetString("SEO_UserRegisterKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        public static string SEO_UserRegisterTitle {
            get {
                return ResourceManager.GetString("SEO_UserRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Your Local Project.
        /// </summary>
        public static string ShareYourLocalProjectH2 {
            get {
                return ResourceManager.GetString("ShareYourLocalProjectH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own host in local system and share it over web..
        /// </summary>
        public static string ShareYourLocalProjectMessage {
            get {
                return ResourceManager.GetString("ShareYourLocalProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        public static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Connected.
        /// </summary>
        public static string StayConnected {
            get {
                return ResourceManager.GetString("StayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Dynamic DNS solution makes it easy to remote access any internet connected device..
        /// </summary>
        public static string StayConnectedMessage {
            get {
                return ResourceManager.GetString("StayConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Host.
        /// </summary>
        public static string ThereIsNoHost {
            get {
                return ResourceManager.GetString("ThereIsNoHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is duplicate.
        /// </summary>
        public static string Username_Is_Duplicate {
            get {
                return ResourceManager.GetString("Username_Is_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid.
        /// </summary>
        public static string Username_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Username_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is wrong.
        /// </summary>
        public static string Username_Or_Password_Is_Wrong {
            get {
                return ResourceManager.GetString("Username_Or_Password_Is_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Dynamic DNS Update Client continually checks for IP address changes in the background and automatically updates the DNS at dnslab whenever it changes..
        /// </summary>
        public static string WinClientMessage {
            get {
                return ResourceManager.GetString("WinClientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your first name.
        /// </summary>
        public static string YourFirstName {
            get {
                return ResourceManager.GetString("YourFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your last name.
        /// </summary>
        public static string YourLastName {
            get {
                return ResourceManager.GetString("YourLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your phone number.
        /// </summary>
        public static string YourPhoneNumber {
            get {
                return ResourceManager.GetString("YourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your username.
        /// </summary>
        public static string YourUsername {
            get {
                return ResourceManager.GetString("YourUsername", resourceCulture);
            }
        }
    }
}
